name: Speedlify Performance Audit

on:
  schedule:
    # Ejecutar diariamente a las 6:00 AM UTC (12:00 AM CST)
    - cron: '0 6 * * *'
  workflow_dispatch: # Permitir ejecución manual
  push:
    branches: [ main ]
    paths:
      - '_data/sites/**'

jobs:
  speedlify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Lighthouse tests
      run: npm run test-pages
      
    - name: Generate API files
      run: npm run generate-api
      
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _data/results/ api/
        git diff --staged --quiet || git commit -m "Update performance results [skip ci]"
        git push
        
    - name: Trigger Netlify Build
      if: success()
      run: |
        curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
